name: Docker CI

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-image
        run: docker build .
